#!/bin/sh
set -x
#
# create our own virtualenv
#
rm -rf virtualenv .tox
virtualenv virtualenv
source virtualenv/bin/activate
pip install --upgrade pip 
pip install --upgrade setuptools
pip install -r requirements.txt
pip install -e .
pip install tox
