#!/bin/sh
if ! sh -c "which virtualenv > /dev/null 2>&1" ; then
    echo "virtualenv not available - have you installed the package?"
    exit 1
fi
set -ex
rm -rf virtualenv .tox
virtualenv virtualenv
source virtualenv/bin/activate
pip install --upgrade pip 
pip install --upgrade setuptools
pip install -r requirements.txt
pip install -e .
pip install tox
exit 0
