#!/bin/bash -x
#
# user-data-master
#
# Launch script for Salt Master ("admin node")

# notify via email that script started to run
EMAIL='presnypreklad@gmail.com'
APACHE_SERVER_IP='10.0.0.60'
instance_id=$(curl http://169.254.169.254/2009-04-04/meta-data/instance-id)
public_ipv4=$(curl http://169.254.169.254/2009-04-04/meta-data/public-ipv4)
mailx -r ceph-auto-aws@github.com -s "$instance_id $public_ipv4 start" $EMAIL

# wait for background zypper to finish
while sleep 5 ; do
    zypper addrepo http://$APACHE_SERVER_IP/SES2/ SES2
    if [[ $? = 0 ]] ; then
        break
    fi
done
zypper addrepo http://download.opensuse.org/repositories/home:smithfarm:susecon/SLE_12/home:smithfarm:susecon.repo
zypper addrepo http://download.opensuse.org/repositories/devel:languages:python/SLE_12/devel:languages:python.repo
zypper --gpg-auto-import-keys ref
zypper -n install salt-master
zypper -n install iperf
zypper -n install ceph-deploy
#zypper -n update

# be the Salt Master
systemctl enable salt-master.service
systemctl start salt-master.service

# announce completion
cat /var/log/cloud-init-output.log | mailx -r ceph-auto-aws@github.com -s "$instance_id $public_ipv4 COMPLETE (cloud-init-output.log)" $EMAIL
