#!/bin/bash -x
#
# user-data-master
#
# Launch script for Salt Master

EMAIL=@@EMAIL@@
BETA_PROGRAM_USERNAME=@@BETA_PROGRAM_USERNAME@@
BETA_PROGRAM_PASSWORD=@@BETA_PROGRAM_PASSWORD@@
BETA_PROGRAM_URL='http://beta.suse.com/private/SUSE-Storage-Beta/2/rc1/'
MEDIA1='SUSE-Enterprise-Storage-2-DVD-x86_64-RC1-Media1.iso'
MEDIA2='SUSE-Enterprise-Storage-2-Updates-x86_64-RC1-Media.iso'

# notify via email that script started to run
instance_id=$(curl http://169.254.169.254/2009-04-04/meta-data/instance-id)
public_ipv4=$(curl http://169.254.169.254/2009-04-04/meta-data/public-ipv4)
message="Salt Master $public_ipv4"
mailx -r ceph-auto-aws@github.com -s "$message user-data start" $EMAIL

# wait for zypper services to settle
# wait for background zypper to finish
while sleep 10 ; do
    zypper services | grep 'SMT-http_smt-ec2_susecloud_net'
    if [[ $? = 0 ]] ; then
        break
    fi
done

# update packages
# wait for background zypper to finish
while sleep 5 ; do
    zypper -n update
    if [[ $? = 0 ]] ; then
        break
    fi
done

# set up directories from which we will serve media repos
mkdir -p /srv/repos
mkdir -p /srv/repos/SES2-media1
mkdir -p /srv/repos/SES2-updates

# download media
cd /srv/repos
wget --user=$BETA_PROGRAM_USERNAME --password=$BETA_PROGRAM_PASSWORD $BETA_PROGRAM_URL$MEDIA1
wget --user=$BETA_PROGRAM_USERNAME --password=$BETA_PROGRAM_PASSWORD $BETA_PROGRAM_URL$MEDIA2

# add media to /etc/fstab
cat <<EOF >>/etc/fstab
/srv/repos/$MEDIA1 /srv/repos/SES2-media1 iso9660 loop 0 0
/srv/repos/$MEDIA2 /srv/repos/SES2-updates iso9660 loop 0 0
EOF

# mount media
mount /srv/repos/SES2-media1
mount /srv/repos/SES2-updates

# add repos
zypper addrepo http://download.opensuse.org/repositories/home:smithfarm:susecon/SLE_12/home:smithfarm:susecon.repo
zypper addrepo http://download.opensuse.org/repositories/devel:languages:python/SLE_12/devel:languages:python.repo
zypper --gpg-auto-import-keys ref

# be the Salt Master
zypper -n install salt-master
systemctl enable salt-master.service
systemctl start salt-master.service

# be the Apache server
zypper -n install apache2
cat <<EOF >/etc/apache2/vhosts.d/admin.conf
<VirtualHost *:80>
    ServerAdmin presnypreklad@gmail.com
    ServerName admin
    DocumentRoot /srv/repos
    HostnameLookups Off 
    UseCanonicalName Off 
    ServerSignature On
    <Directory /srv/repos>
        Options Indexes FollowSymLinks
        AllowOverride All 
        Require all granted
    </Directory>
</VirtualHost>
EOF
systemctl enable apache2.service
systemctl start apache2.service

# salt-related scripts
cat <<EOF >/root/bin/salt-setup-admin.sh
DELEGATE=\$1 ; salt -C "G@delegate:\$DELEGATE and G@role:admin" state.sls ceph-admin
EOF
cat <<EOF >/root/bin/salt-setup-mons.sh
DELEGATE=\$1 ; salt -C "G@delegate:\$DELEGATE and G@role:mon" state.sls ceph-mon
EOF
chmod 755 /root/bin/*

# announce completion
mailx -r ceph-auto-aws@github.com -s "$message user-data complete, rebooting" $EMAIL

systemctl reboot
