#!/bin/bash -x
#
# user-data-minion
#
# Launch script for Salt Minion

# wait for background zyppers to finish
while sleep 5 ; do
    zypper --non-interactive refresh
    if [[ $? = 0 ]] ; then
        break
    fi
done

# update packages
zypper --non-interactive update --auto-agree-with-licenses

#set up resolv.conf
echo "search @@REGION@@.compute.internal" >> /etc/resolv.conf

# salt minion
zypper -n install salt-minion # creates /etc/salt/minion.d directory
MINION_CONF=/etc/salt/minion.d/ceph.conf
cat <<EOF > $MINION_CONF
master: @@MASTER_IP@@
grains:
  delegate: @@DELEGATE@@
  role: @@ROLE@@
  node_no: @@NODE_NO@@
  deepsea: True
EOF
chown root:root $MINION_CONF
chmod 0644 $MINION_CONF
systemctl enable salt-minion.service
systemctl start salt-minion.service

# make DeepSea grains available to bash scripts running on the minion
BASEDIR=/etc/susecon2017
mkdir -p $BASEDIR
cat <<EOF > $BASEDIR/local_master
ip-10-0-@@DELEGATE@@-10
EOF
mkdir -p $BASEDIR/grains
cat <<EOF > $BASEDIR/grains/delegate
@@DELEGATE@@
EOF
cat <<EOF > $BASEDIR/grains/role
@@ROLE@@
EOF
cat <<EOF > $BASEDIR/grains/node_no
@@NODE_NO@@
EOF
chmod -R o+r /etc/susecon2017
