#!/bin/bash -x
#
# user-data-root-master
#
# Launch script for Root Master

# update packages
# wait for background zyppers to finish
while sleep 5 ; do
    zypper -n update
    if [[ $? = 0 ]] ; then
        break
    fi
done

#set up resolv.conf
echo "search @@REGION@@.compute.internal" >> /etc/resolv.conf

# set up ntpd
cat <<EOF >/etc/ntp.conf
restrict -4 default notrap nomodify nopeer noquery
restrict -6 default notrap nomodify nopeer noquery
restrict 127.0.0.1
restrict ::1
restrict 10.0.0.0 mask 255.255.0.0
driftfile /var/lib/ntp/drift/ntp.drift # path for drift file
logfile   /var/log/ntp
keys /etc/ntp.keys
trustedkey 1
requestkey 1
controlkey 1
server 0.amazon.pool.ntp.org iburst
server 1.amazon.pool.ntp.org iburst
server 2.amazon.pool.ntp.org iburst
server 3.amazon.pool.ntp.org iburst
EOF
systemctl enable ntpd.service
systemctl restart ntpd.service

# install rpms
zypper --gpg-auto-import-keys refresh
zypper --non-interactive --no-gpg-checks install --no-recommends \
    git-core \
    salt-master

# restart salt-master
systemctl enable salt-master.service
systemctl restart salt-master.service

# generate SSH key
mkdir -p /root/.ssh
chmod 700 /root/.ssh
ssh-keygen -b 1024 -t rsa -q -N "" -f /root/.ssh/id_rsa

# set motd
cat <<EOF >/etc/motd
This is the Root Master node.

Have a lot of fun...
EOF

# clone Salt states
mkdir -p /srv/salt
cd /root
git clone --depth 1 https://github.com/smithfarm/ceph-auto-aws.git
cp -a /root/ceph-auto-aws/states/* /srv/salt

# inject SSH key
cp /root/.ssh/id_rsa* /srv/salt
chmod 644 /srv/salt/id_rsa.pub
chmod 600 /srv/salt/id_rsa

# change ownership to salt user for files in /srv/salt
chown -R salt.salt /srv/salt

## install ttyrec
#zypper ar http://download.opensuse.org/repositories/utilities/openSUSE_Leap_42.3/utilities.repo
#zypper --gpg-auto-import-keys ref
#zypper -n install ttyrec

# wait for other instances to initialize
sleep 30

# accept delegate minion keys
salt-key -Ay
