#!/bin/bash -x
#
# user-data-nodes
#
# Launch script for Ceph nodes

zypper -n addrepo http://download.opensuse.org/repositories/filesystems:ceph:hammer/openSUSE_Leap_42.1/filesystems:ceph:hammer.repo
zypper --gpg-auto-import-keys refresh
zypper -n install ntp salt-minion

cat <<EOF >>/etc/ntp.conf
server 0.amazon.pool.ntp.org iburst
server 1.amazon.pool.ntp.org iburst
server 2.amazon.pool.ntp.org iburst
server 3.amazon.pool.ntp.org iburst
EOF
systemctl enable ntpd.service

systemctl enable salt-minion.service
MINION_CONF=/etc/salt/minion.d/ceph.conf
cat <<EOF > $MINION_CONF
master: @@MASTER_IP@@
grains:
  delegate: @@DELEGATE@@
  role: @@ROLE@@
  node_no: @@NODE_NO@@
EOF
chown root:root $MINION_CONF
chmod 0644 $MINION_CONF

zypper -n update

systemctl reboot
