#!/bin/bash -x
#
# user-data-nodes
#
# Launch script for Ceph nodes

zypper -n addrepo http://download.opensuse.org/repositories/systemsmanagement:saltstack/SLE_12_SP1/systemsmanagement:saltstack.repo
zypper -n addrepo http://ip-10-0-0-10/iscsi-repo iscsi-repo
zypper -n addrepo http://ip-10-0-0-10/SES2-media1 SES2-media1
zypper -n addrepo http://ip-10-0-0-10/SES2-update SES2-update
zypper --gpg-auto-import-keys refresh
zypper -n install ntp salt-minion

cat <<EOF >>/etc/ntp.conf
server 0.amazon.pool.ntp.org iburst
server 1.amazon.pool.ntp.org iburst
server 2.amazon.pool.ntp.org iburst
server 3.amazon.pool.ntp.org iburst
EOF
systemctl enable ntpd.service

systemctl enable salt-minion.service
MINION_CONF=/etc/salt/minion.d/ceph.conf
cat <<EOF > $MINION_CONF
master: @@MASTER_IP@@
grains:
  delegate: @@DELEGATE@@
  role: @@ROLE@@
  node_no: @@NODE_NO@@
EOF
chown root:root $MINION_CONF
chmod 0644 $MINION_CONF

zypper -n update

zypper --no-gpg-checks --non-interactive install --oldpackage kernel-default-3.12.51-60.25.1.10225.0.PTF.964727.x86_64
zypper --non-interactive remove kernel-default-3.12.49
zypper --non-interactive remove kernel-default-3.12.53

systemctl reboot
