#!/bin/bash -x
#
# user-data-master
#
# Launch script for Salt Master

# update packages
# wait for background zyppers to finish
while sleep 5 ; do
    zypper -n update
    if [[ $? = 0 ]] ; then
        break
    fi
done

# set up ntpd
cat <<EOF >/etc/ntp.conf
restrict -4 default notrap nomodify nopeer noquery
restrict -6 default notrap nomodify nopeer noquery
restrict 127.0.0.1
restrict ::1
restrict 10.0.0.0 mask 255.255.0.0
driftfile /var/lib/ntp/drift/ntp.drift # path for drift file
logfile   /var/log/ntp
keys /etc/ntp.keys
trustedkey 1
requestkey 1
controlkey 1
server 0.amazon.pool.ntp.org iburst
server 1.amazon.pool.ntp.org iburst
server 2.amazon.pool.ntp.org iburst
server 3.amazon.pool.ntp.org iburst
EOF
systemctl enable ntpd.service
systemctl start ntpd.service

# set up salt master
zypper -n install salt-master
systemctl enable salt-master.service
systemctl start salt-master.service

# install git
SUSEConnect -p sle-sdk/12.2/x86_64
zypper --gpg-auto-import-keys ref
zypper -n install --no-recommends git

# generate SSH key
mkdir -p /root/.ssh
chmod 700 /root/.ssh
ssh-keygen -b 1024 -t rsa -q -N "" -f /root/.ssh/id_rsa

# set motd
cat <<EOF >/etc/motd
This is the Salt Master.

Have a lot of fun...
EOF

# clone salt recipes
cd /srv
git clone https://github.com/smithfarm/susecon-salt-master salt

# inject SSH key
cp /root/.ssh/id_rsa* /srv/salt
chmod 644 /srv/salt/id_rsa*
