#!/bin/bash -x
#
# user-data-master
#
# Launch script for Salt Master

# update packages
# wait for background zyppers to finish
while sleep 5 ; do
    zypper -n update
    if [[ $? = 0 ]] ; then
        break
    fi
done

# set up ntpd
cat <<EOF >>/etc/ntp.conf
server 0.amazon.pool.ntp.org iburst
server 1.amazon.pool.ntp.org iburst
server 2.amazon.pool.ntp.org iburst
server 3.amazon.pool.ntp.org iburst
EOF
systemctl enable ntpd.service
systemctl start ntpd.service

# set up salt master
zypper -n install salt-master
systemctl enable salt-master.service
systemctl start salt-master.service

zypper addrepo http://download.opensuse.org/repositories/home:smithfarm:susecon/SLE_12_SP1/home:smithfarm:susecon.repo
zypper --gpg-auto-import-keys ref
zypper -n install susecon-salt-master
